# 配置详情请参考：https://docs.halo.run/zh/developer-guide/theme/config-files
genernal:
  label: 基本设置
  items:
    index_notice_title:
      name: index_notice_title
      label: 首页公告标题
      type: text
      default: 'Hello Halo!'
    index_notice_content:
      name: index_notice_content
      label: 首页公告内容
      type: textarea
      default: '一款 Terminal 风格的 Halo 主题'
    theme_color:
      name: theme_color
      label: 主题颜色
      type: select
      default: orange
      options:
        - value: orange
          label: 橙色
        - value: blue
          label: 蓝色
        - value: green
          label: 绿色
        - value: pink
          label: 粉色
        - value: red
          label: 红色
